spring:
  application:
    name: GATEWAY-SERVICE

zuul:
  ignored-services: "*"
  routes:
    AUTH-SERVICE:
      service-id: AUTH-SERVICE
      path: /api/v1/auth/**
      strip-prefix: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8888/eureka/}
  instance:
    preferIpAddress: true

server:
  port: 8181
